#!/usr/bin/env bash
#ensure we're using zsh as the main shell
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
chsh -s /usr/bin/zsh

#install files and folders to the right place in $HOME
rm  ~/.zshrc
ln -s ~/dotfiles/git/ ~/.git 
ln -s ~/dotfiles/vim ~/.vim 
ln -s ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf 
ln -s ~/dotfiles/vim/.vimrc ~/.vimrc 
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc 

